// Code generated by entc, DO NOT EDIT.

package operator

const (
	// Label holds the string label denoting the operator type in the database.
	Label = "operator"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldHashedPassword holds the string denoting the hashedpassword field in the database.
	FieldHashedPassword = "hashed_password"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// Table holds the table name of the operator in the database.
	Table = "operators"
)

// Columns holds all SQL columns for operator fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldHashedPassword,
	FieldRole,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
